name: Deploy to Sandbox
on:
  push:
    branches:
      - Nanma
    paths:
      - 'force-app/**'
  workflow_dispatch:    # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # ... other steps
